{% set name = "pyworld" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyworld-{{ version }}.tar.gz
  sha256: 106c70ee7a7d8c9ba488d8022f2033706929a40f0264256b8e87da5aab98303a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
  run:
    - cython >=0.24.0
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyworld
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder
  summary: PyWorld is a Python wrapper for WORLD vocoder.
  license: MIT
  license_file: LICENSE
  description: |
    PyWorld is a wrapper for WORLD, which is free software for
     high-quality speech analysis, manipulation and synthesis. It can
     estimate fundamental frequency (F0), aperiodicity and spectral
     envelope, and also generate the speech like input speech with only
     estimated parameters.

extra:
  recipe-maintainers:
    - thewchan
